print("You are about to play a Mad Lib. \n" "You will have to type in random pro-nouns, adjectives etc. \n" "They will then be put into a story and you will see how it turns out.")
n = input ("Please enter a name for your character>")
p = input ("Please enter a place>")
adv = input ("Please enter an adverb>")
nou = input ("Please enter a noun>")
adj = input ("Please enter adjective>")
an = input ("Please enter an animal>")
objt = input ("Please enter an object for your character to weild>") 
v = input ("Please enter a verb>")
pl = input ("Please enter another place>")
end = input ("Please enter a car brand>")
print(f"It was just a normal day in {p} when {n} saw something intresting \n" "{n} {adj} ran over and {p} grabed a {objt} \n" "When {n} realized it was an {an} {n} ran to their {end} \n" "{n} went to the {pl} and {v} to help the {adv} {an}  \n" "{n} then returned to {nou} and saved the {an}. THE END")
#make sure you have a f string in every line of a quote w/variables for example (f"hjdsahjhajkh n gfgdgd. \n" f"hfjdskhj adj sdhsdkjshjk") 